//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hzcl.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<short> DelFlag { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Remark { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string ActionMethodName { get; set; }
        public string Sort { get; set; }
        public Nullable<short> ActionTypeName { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<int> IconWeidth { get; set; }
        public Nullable<int> IconHeight { get; set; }
    }
}
