//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hzcl.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public System.DateTime RegTime { get; set; }
        public Nullable<byte> DelFlag { get; set; }
        public string Remark { get; set; }
        public string Sort { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
